receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  otlphttp:
    endpoint: "http://tempo:4318" # Gửi traces đến Tempo
  prometheus:
    endpoint: "0.0.0.0:8889" # Xuất metrics cho Prometheus
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push" # Gửi logs đến Loki
  zabbix_exporter:
    endpoint: "http://zabbix_exporter:5000/otel" # Endpoint chuẩn theo script

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, zabbix_exporter] # ✅ Gửi đồng thời Prometheus & Zabbix

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
